### PR TITLE
Add file helloworld.txt

### PR DESCRIPTION
**Pull request by NoureddineAJ**
Hello

### CODE REVIEW

**Comment by NoureddineAJ** [comment]
Can I push my thing?

**Review by BenjaminKnol — COMMENTED** [review]
Do we need another empty file in the master?

**Comment by NoureddineAJ** [comment]
Yess

**Comment by NoureddineAJ** [comment]
> Do we need another empty file in the master?

Yes, because it's necessary for out endproduct.

**Review by BenjaminKnol — APPROVED** [review]
Apperently we need this to finish the endproduct in a timely manner

**Pull request merged**
